name: CustomEnchantments
version: 1.0.0
author: Scusemua
main: me.Scusemua.customenchantments.core.Main
depend: [Vault, ArmorEquipEvent]

commands:
  customenchantments:
    description: Add a custom enchantment to a given item.
    useage: /<command>
    aliases: [customenchants, customenchantment, customenchant]
    permissions: CustomEnchantments.addenchantment